### ISSUE TITLE
set fluid in config will be replace to default setting after lanuch the game

### ISSUE THREAD

**Issue by QLNPLUS** [oierbravo/create-mechanical-chicken#3]
set fluid in config will be replace to default setting after lanuch the game.
I tried to set the fluid to 'createaddition:seed_oil' but after i lanuch the game, the config file reset, other setting like seedOilEnabled and Stress impact didnt, just the fluid.

mod version [1.1.1.h-48]

**Comment by QLNPLUS** [comment]
set to "water" can work, and when i set to milk, the config reset again

**Comment by oierbravo** [comment]
Thanks!
Im working on it.

**Comment by oierbravo** [comment]
I think just fixed the compat issue.
Now accept #forge:plantoil for compat with createadditions & diesel generators.
